theme: jekyll-theme-architect
title: KayleeSG Blog
author: kayleesg
email: kaylee.schneegass@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal portfolio / blogging site where I share my journey in world of Cyber Security.
  I will post articles on my journey as well as notable projects that I want to be visible.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  kayleesg # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
